import {readFile,writeFile,readdir,mkdir,rm,cp} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {load} from 'cheerio';
import {escape as e,frontmatter,basePath,renderMarkdown} from './lib.mjs';
import {calculations} from './calculations.mjs';
import {symetrixMatrixV01} from './symetrix.mjs';
import {symetrixMatrixV02} from './symetrix-v02.mjs';
import {symetrixMatrixV03} from './symetrix-v03.mjs';
import {evidenceCoverage} from './evidence.mjs';
import {runDenominatorEngine} from './denominator-engine.mjs';
import {loadContent} from './content.mjs';

export const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=file=>readFile(path.join(root,file),'utf8');
const config=JSON.parse(await read('config.json'));
for(const key of ['version','author','publishedAt','updated','dataCutoff','origin','basePath'])if(!config[key])throw new Error(`Missing config ${key}`);
const base=basePath(process.env.BASE_PATH??config.basePath);
const origin=process.env.SITE_ORIGIN??config.origin;
if(!/^https?:\/\/[^/]+$/.test(origin))throw new Error('SITE_ORIGIN must be an origin without path');
const u=route=>base+route;
const displayDate=value=>new Date(value+'T00:00:00Z').toLocaleDateString('fi-FI',{timeZone:'UTC'});
const dist=path.join(root,'dist');
await rm(dist,{recursive:true,force:true});
await mkdir(dist,{recursive:true});
await cp(path.join(root,'assets'),path.join(dist,'assets'),{recursive:true});
async function put(file,text){const dest=path.join(dist,file);await mkdir(path.dirname(dest),{recursive:true});await writeFile(dest,text);}

const {pages,sources,documents,observations,publication,legacyAnchors,chapters}=await loadContent();
const questions=await Promise.all((await readdir(path.join(root,'content/questions'))).sort().filter(f=>f.endsWith('.md')).map(async f=>frontmatter(await read('content/questions/'+f))));
const evidenceRaw=await read('data/evidence-index.jsonl');
const evidence=evidenceRaw.trim().split(/\n+/).filter(Boolean).map(JSON.parse);
const metricRegistry=JSON.parse(await read('data/metric-registry.json'));
const employmentBoundaries=JSON.parse(await read('data/employment-boundaries.json'));
const energyWaterScenarios=JSON.parse(await read('data/energy-water-scenarios.json'));
const resourceFlowTaxonomy=JSON.parse(await read('data/resource-flow-taxonomy.json'));
const denominatorRecipes=JSON.parse(await read('data/denominator-recipes.json'));
const auditGoals=JSON.parse(await read('data/audit-goals.json'));
let links=[];try{links=JSON.parse(await read('data/link-check.json')).results;}catch(error){if(error.code!=='ENOENT')throw error;}
const statuses=new Map(links.map(r=>[r.url,r]));
const pageBySlug=new Map(pages.map(page=>[page.meta.slug,page]));
const routes=new Set();
for(const {meta} of pages){for(const key of ['title','slug','route','language','status','published','updated','description','layout'])if(meta[key]===undefined)throw new Error(`Missing ${key}`);if(!/^\/(?:[a-z0-9-]+\/)*$/.test(meta.route)||routes.has(meta.route))throw new Error('Invalid/duplicate route');routes.add(meta.route);}
if(!pageBySlug.has('datakeskukset')||publication.canonicalRoute!==pageBySlug.get('datakeskukset').meta.route)throw new Error('Canonical report route mismatch');
const sourceIDs=new Set([...sources,...documents].map(s=>s.id));
const classes=['tuettu','osittain tuettu','epätarkka','avoin','näyttöä ei löytynyt'];
questions.forEach(({meta,body},i)=>{if(meta.id!==`A${String(i+1).padStart(2,'0')}`||!classes.includes(meta.classification)||!meta.question||!meta.rationale||!meta.openData||!meta.sourceRefs.length||!body)throw new Error('Invalid question');meta.sourceRefs.forEach(id=>{if(!sourceIDs.has(id))throw new Error(`Unknown source ${id}`);});});
if(questions.length!==11)throw new Error('Expected 11 questions');

const nav=[['Raportti',publication.canonicalRoute],['Väitteet A01–A11','/analyysit/datakeskukset/vaiteet/'],['Lähteet ja laskelmat','/analyysit/datakeskukset/lahteet/'],['Menetelmä','/menetelma/'],['Muutokset','/muutokset/']];
function sectionNav(route){return nav.map(([name,target])=>{const current=route===target||(target===publication.canonicalRoute&&route===publication.compatibilityRoute);return `<a href="${u(target)}"${current?' aria-current="page"':''}>${name}</a>`;}).join('');}
function tableOfContents(headings){const h=headings.filter(x=>x.level===2);return h.length<2?'':`<nav class="contents" aria-label="Tällä sivulla"><strong>Tällä sivulla</strong><ul>${h.map(x=>`<li><a href="#${e(x.id)}">${e(x.text)}</a></li>`).join('')}</ul></nav>`;}
function toolsBar(){return `<div class="tools"><button type="button" class="js-only" data-print>Tulosta / tallenna PDF</button><a href="${u('/downloads/datakeskukset.md')}" download>Lataa raportti (.md)</a></div>`;}
function articleJsonLd(meta,canonicalRoute){return JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:meta.title,description:meta.description,inLanguage:'fi',datePublished:config.publishedAt,dateModified:meta.updated,author:{'@type':'Organization',name:config.author,url:origin+u('/')},publisher:{'@type':'Organization',name:config.author,url:origin+u('/')},mainEntityOfPage:origin+u(canonicalRoute),image:origin+u('/assets/og.png')}).replaceAll('<','\\u003c');}
function template(meta,content,toc='',options={}){
  const article=meta.layout!=='home'&&meta.layout!=='404';const side=['article','questions','sources','report'].includes(meta.layout);const canonicalRoute=options.canonicalRoute??meta.route;const robots=options.robots??(meta.layout==='404'?'noindex':'index,follow');
  const visibleMeta=`Tekijä ${e(config.author)} · Versio ${e(config.version)} · Julkaistu <time datetime="${config.publishedAt}">${displayDate(config.publishedAt)}</time> · Päivitetty <time datetime="${meta.updated}">${displayDate(meta.updated)}</time> · Aineisto <time datetime="${config.dataCutoff}">${displayDate(config.dataCutoff)}</time>`;
  const inner=article?`${side?`<aside class="side"><div class="side-inner"><strong>Datakeskukset</strong><nav aria-label="Julkaisun osiot">${sectionNav(meta.route)}</nav></div></aside><div><details class="mobile-nav"><summary>Julkaisun osiot</summary><nav aria-label="Julkaisun osiot mobiilissa">${sectionNav(meta.route)}</nav></details>`:''}<main id="sisalto" tabindex="-1" class="${side?'article':'standalone'}"><header class="article-head"><h1>${e(meta.title)}</h1><p class="lead">${e(meta.description)}</p><p class="meta">${visibleMeta}</p><p class="publication-state">Julkaisutila: ${meta.published?'julkaistu':'julkaisukandidaatti – julkaisuportti suljettu'}</p></header>${toc}<div class="prose">${content}</div>${toolsBar()}<p class="print-note">${e(config.author)} · ${e(origin+u(canonicalRoute))} · aineisto ${displayDate(config.dataCutoff)}</p></main>${side?'</div>':''}`:`<main id="sisalto" tabindex="-1">${content}</main>`;
  const structured=article?`<script type="application/ld+json">${articleJsonLd(meta,canonicalRoute)}</script>`:'';
  return `<!doctype html><html lang="fi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${e(meta.title)} | Symetra</title><meta name="description" content="${e(meta.description)}"><meta name="robots" content="${robots}"><link rel="canonical" href="${e(origin+u(canonicalRoute))}"><meta property="og:type" content="${article?'article':'website'}"><meta property="og:locale" content="fi_FI"><meta property="og:site_name" content="Symetra"><meta property="og:title" content="${e(meta.title)}"><meta property="og:description" content="${e(meta.description)}"><meta property="og:url" content="${e(origin+u(canonicalRoute))}"><meta property="og:image" content="${e(origin+u('/assets/og.png'))}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Symetra — Datakeskusten taloudellisten ja yhteiskunnallisten vaikutusten auditointi"><meta name="twitter:card" content="summary_large_image">${structured}<link rel="stylesheet" href="${u('/assets/site.css')}"><script defer src="${u('/assets/site.js')}"></script></head><body class="${meta.layout==='home'?'home':'reading'}"><a class="skip" href="#sisalto">Siirry sisältöön</a><div class="shell"><header class="site-header"><a class="brand" href="${u('/')}">Symetra</a><nav aria-label="Päänavigaatio">${sectionNav(meta.route)}</nav></header><div class="${side?'layout':''}">${inner}</div><footer class="site-footer"><a class="brand" href="${u('/')}">Symetra</a><span>Lähteet näkyviin. Rajaukset näkyviin.</span></footer></div></body></html>`;
}
function questionHTML({meta,body},{headingLevel=2,embedded=false}={}){const h=`h${headingLevel}`;return `<section class="question" id="${meta.id}">${embedded?`<span class="legacy-anchor" id="raportti-${meta.id}" aria-hidden="true"></span>`:''}<${h}>Tutkimuskysymys ${meta.id}: ${e(meta.question)}</${h}><p class="verdict">Alkuperäisen väitteen näyttö: <strong>${e(meta.classification)}</strong></p>${renderMarkdown(body,base).html}</section>`;}
function availability(s){const r=statuses.get(s.url);return !r?'Teknistä saatavuutta ei ole tarkistettu tässä buildissa.':`Tekninen tarkistus ${e(r.checked)}: ${e(r.result)}${r.status?` (HTTP ${r.status})`:''}.`;}
function sourcesHTML(){return sources.map(s=>`<section class="source-item" id="${s.id}"><h3>${s.id} · <a href="${e(s.url)}">${e(s.title)}</a></h3><p>${e(s.verification)}</p><p>${availability(s)}</p></section>`).join('')+`<h3 id="asiakirjat">HEL16:n asiakirjat</h3>`+documents.map(s=>`<section class="source-item" id="${s.id}"><h3>${s.id} · ${e(s.title)}</h3><p>${e(s.note)} ${s.pages} PDF-sivua. <a href="${e(s.url)}">Avaa asian tietopalvelusivu</a>.</p><p>${availability(s)}</p><details><summary>Tiedoston SHA-256-tiiviste</summary><p><code>${s.sha256}</code></p></details></section>`).join('');}
function withLegacyAnchors(route,html,also=[]){const $=load(html,null,false);const ids=new Set($('[id]').toArray().map(x=>$(x).attr('id')));const aliases=[...new Set([...(legacyAnchors[route]||[]),...also.flatMap(r=>legacyAnchors[r]||[])])].filter(id=>!ids.has(id));return aliases.map(id=>`<span class="legacy-anchor" id="${e(id)}" aria-hidden="true"></span>`).join('')+$.html();}
function chapterParts(id){const raw=chapters.get(id);const heading=raw.match(/^## (.+)\r?\n/);if(!heading)throw new Error(`Report chapter ${id}: missing H2 title`);return {title:heading[1],body:raw.slice(heading[0].length),raw};}
function shifted(body){return body.replace(/^(#{2,5}) /gm,'#$1 ');}

let reportHTML='';let reportMD=`# ${pageBySlug.get('datakeskukset').meta.title}\n\nTekijä: ${config.author}\n\nVersio: ${config.version} · Julkaistu: ${displayDate(config.publishedAt)} · Päivitetty: ${displayDate(config.updated)} · Aineisto: ${displayDate(config.dataCutoff)}\n\n`;const reportToc=[];
for(const section of publication.reportSections){const className=`chapter report-section report-section--${section.id} report-group--${section.group}`;if(section.kind==='chapter'){const {title,body,raw}=chapterParts(section.id);reportHTML+=`<section class="${className}" id="raportti-${section.id}"><h2>${e(title)}</h2>${renderMarkdown(body,base,section.id+'-').html}</section>`;reportMD+=`\n${raw.trim()}\n`;reportToc.push({id:'raportti-'+section.id,level:2,text:title});continue;}const page=pageBySlug.get(section.id);if(section.id==='datakeskukset'){const rendered=renderMarkdown(page.body,base,'datakeskukset-');reportHTML+=`<section class="${className}" id="raportti-${section.id}">${rendered.html}</section>`;reportMD+=`${page.body.trim()}\n`;reportToc.push(...rendered.headings.filter(h=>h.level===2));continue;}const body=shifted(page.body);reportHTML+=`<section class="${className}" id="raportti-${section.id}"><h2>${e(page.meta.title)}</h2>${renderMarkdown(body,base,section.id+'-').html}`;reportMD+=`\n## ${page.meta.title}\n\n${body.trim()}\n`;if(section.kind==='questions'){reportHTML+=questions.map(q=>questionHTML(q,{headingLevel:3,embedded:true})).join('');reportMD+=questions.map(q=>`\n### ${q.meta.id}: ${q.meta.question}\n\nLuokka: ${q.meta.classification}\n\n${q.body.trim()}\n`).join('');}reportHTML+='</section>';reportToc.push({id:'raportti-'+section.id,level:2,text:page.meta.title});}
const sourceAppendix=`<section class="chapter print-appendix" id="tulostus-lahteet"><h2>Lähdeliite</h2>${sourcesHTML()}</section>`;for(const appendix of publication.downloadAppendices){const page=pageBySlug.get(appendix.id);const body=shifted(page.body);reportMD+=`\n## ${page.meta.title}\n\n${body.trim()}\n`;reportMD+=sources.map(s=>`\n### ${s.id}: ${s.title}\n\n${s.url}\n\n${s.verification}\n`).join('');reportMD+=documents.map(d=>`\n### ${d.id}: ${d.title}\n\n${d.note}\n\n${d.url}\n\nSHA-256: ${d.sha256}\n`).join('');}
reportMD=reportMD.replace(/\]\(\/(?!\/)([^)]*)\)/g,(_,p)=>`](${origin+u('/'+p)})`).replace(/\]\(#(S\d+)\)/g,(_,id)=>`](${origin+u('/analyysit/datakeskukset/lahteet/#'+id)})`);
const canonicalPage=pageBySlug.get('datakeskukset');const sharedReportHTML=withLegacyAnchors(publication.canonicalRoute,reportHTML+sourceAppendix,[publication.compatibilityRoute]);await put(publication.canonicalRoute.slice(1)+'index.html',template(canonicalPage.meta,sharedReportHTML,tableOfContents(reportToc),{canonicalRoute:publication.canonicalRoute}));const compatibilityMeta={...canonicalPage.meta,route:publication.compatibilityRoute};await put(publication.compatibilityRoute.slice(1)+'index.html',template(compatibilityMeta,sharedReportHTML,tableOfContents(reportToc),{canonicalRoute:publication.canonicalRoute,robots:'noindex,follow'}));
for(const page of pages){const {meta,body}=page;if(meta.route===publication.canonicalRoute)continue;let {html,headings}=renderMarkdown(body,base);let toc=tableOfContents(headings);if(meta.layout==='home'){const $=load(html);const ps=$('body>p');html=`<section class="hero"><h1>${e(meta.title)}</h1><p class="lead">${ps.eq(0).html()}</p><a class="button" href="${u(publication.canonicalRoute)}">Lue raportti</a></section><section class="feature"><span class="feature-label">Ensimmäinen analyysi</span><div><h2>${$('h2').text()}</h2><p>${ps.eq(2).html()}</p>${ps.eq(3).html()}</div></section><div class="principles">${$('h3').toArray().map(h=>`<section><h2>${$(h).text()}</h2>${$(h).next('p').toString()}</section>`).join('')}</div>`;}if(meta.layout==='questions'){toc=tableOfContents(questions.map(q=>({id:q.meta.id,level:2,text:q.meta.id+' · '+q.meta.question})));html+=questions.map(q=>questionHTML(q)).join('');}if(meta.layout==='sources')html+=sourcesHTML();html=withLegacyAnchors(meta.route,html);await put(meta.route==='/'?'index.html':meta.route.slice(1)+'index.html',template(meta,html,toc));}
await put('404.html',template({title:'Sivua ei löytynyt',description:'Osoite on voinut muuttua. Julkaisun sisältö löytyy etusivulta ja analyysin hakemistosta.',route:'/404.html',updated:config.updated,layout:'404'},`<h1>Sivua ei löytynyt</h1><p><a href="${u('/')}">Palaa Symetran etusivulle</a> tai <a href="${u(publication.canonicalRoute)}">avaa datakeskusanalyysi</a>.</p>`));
await put('downloads/datakeskukset.md',reportMD+'\n');await put('downloads/evidence-index.jsonl',evidenceRaw.endsWith('\n')?evidenceRaw:evidenceRaw+'\n');
for(const [name,data] of [['sources',sources],['documents',documents],['observations',observations],['questions',questions.map(q=>({...q.meta,body:q.body}))],['calculations',calculations()],['symetrix-v0.1',symetrixMatrixV01()],['symetrix-v0.2',symetrixMatrixV02()],['symetrix-v0.3',symetrixMatrixV03()],['evidence-index',evidence],['evidence-coverage',evidenceCoverage(evidence)],['metric-registry',metricRegistry],['employment-boundaries',employmentBoundaries],['energy-water-scenarios',energyWaterScenarios],['resource-flow-taxonomy',resourceFlowTaxonomy],['denominator-engine-v0.1',runDenominatorEngine(evidence,denominatorRecipes)],['denominator-recipes',denominatorRecipes],['audit-goals',auditGoals]])await put(`downloads/${name}.json`,JSON.stringify(data,null,2)+'\n');
const csvValue=x=>'"'+String(x).replaceAll('"','""')+'"';await put('downloads/sources.csv','\ufeff'+[['id','title','url','verification'],...sources.map(s=>[s.id,s.title,s.url,s.verification])].map(row=>row.map(csvValue).join(',')).join('\r\n'));await put('.nojekyll','');
await put('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(p=>p.meta.route).map(r=>`<url><loc>${e(origin+u(r))}</loc><lastmod>${config.updated}</lastmod></url>`).join('')}</urlset>`);
await put('build-meta.json',JSON.stringify({version:config.version,author:config.author,publishedAt:config.publishedAt,updated:config.updated,dataCutoff:config.dataCutoff,basePath:base,origin,canonicalRoute:publication.canonicalRoute,compatibilityRoute:publication.compatibilityRoute,routes:[...routes,publication.compatibilityRoute],questionCount:questions.length,sourceCount:sources.length,observationCount:observations.length,reportSectionCount:publication.reportSections.length},null,2));
console.log(`Built ${pages.length+2} HTML pages; ${questions.length} questions; ${sources.length} web sources. Base path: ${base||'/'}`);
